system-ghc: true

resolver: lts-18.21
packages:
- .
# extra-deps: []
# flags: {}
# extra-package-dbs: []

##############################################################################
## Resolvers
## (see https://www.stackage.org/)

## ghc-8.10.7 -> lts-18.21
## ghc-8.10.6 -> lts-18.8
## ghc-8.10.4 -> lts-18.6
## ghc-8.8.4  -> lts-16.31
## ghc-8.8.2  -> lts-15.3
